e_hac/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern
from .views import add_ehac, ehac_list

urlpatterns = [
    path('add-ehac', add_ehac, name='add_ehac'),
    path('ehac-list', ehac_list, name='ehac_list')
]

user_regis_login/urls.py
from django.urls import path
from .views import  user_login, user_logout

urlpatterns = [
  # path('', index, name='index'),
  path('login/', user_login, name='user_login'),
  path('logout/', user_logout, name='user_logout'),
  # path('form/', add_note, name='add_list'),
]

uts_e02/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('aplikasi_vaksin.urls')),
    path('user/', include('user_regis_login.urls')),
    path('user/', include('admin_tambah_faskes.urls')),
    path('user/', include('form_pendaftaran.urls')),
    path('user/', include('Daftar_PCR.urls')),
    path('user/', include('e_hac.urls')),
    path('user/', include('user_profile.urls')),
]
"""
mungkin kalau yang berhubungan dengan user, awalan path bisa pakai 'user/' aja, biar sama gitu. misal path('user/' include('profile.urls')). yang penting di urls tiap app dibedakan gitu. misal path('dashboard/', dashboard, name='dashboard') untuk dashboard, path('self_assesment/', self_assesment, name='self_assesment') untuk self_assesment, dst dalam app yang sama misal profile
"""

aplikasi_vaksin/models.py
from django.db import models
from admin_tambah_faskes.models import Lokasi, TanggalWaktu, JenisVaksin
# Create your models here.
class User(models.Model):
    email = models.EmailField()
    password = models.CharField(max_length=30)
    name = models.CharField(max_length=30)
    no_hp = models.CharField(max_length=12)
    usia = models.CharField(max_length=3)
    nik = models.CharField(max_length=15)
    domisili = models.CharField(max_length=50)
    lokasi = models.ForeignKey(Lokasi, on_delete=models.SET_NULL, blank=True, null=True)
    tanggal = models.ForeignKey(TanggalWaktu, on_delete=models.SET_NULL, blank=True, null=True)
    jenis = models.ForeignKey(JenisVaksin, on_delete=models.SET_NULL, blank=True, null=True)
    def __str__(self) -> str:
        return f"{self.name} | {self.email}"

user_regis_login/models.py
from django.db import models

# Create your models here.

user_regis_login/views.py
from django.http import response
from django.http.response import HttpResponseRedirect
from django.contrib.auth.models import User as DjangoUser
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import redirect, render
from aplikasi_vaksin.models import User
from json import dumps

def user_login(request):
  users = User.objects.all().values()
  user_as_json = []
  for user in users:
    user_as_json.append({'email':user['email'], 'password': user['password']})
  response = {
    'users' : users,
    'json': dumps(user_as_json),
  }
  if request.method == "POST":
    # saat berhasil login, return ke home
    email = request.POST['email']
    password = request.POST['password']
    user = authenticate(request, username=email, password=password)
    if user is not None:
      login(request, user)
      return HttpResponseRedirect('/')
  return render(request, "user_login/index.html", response)

def user_logout(request):
  logout(request)
  return HttpResponseRedirect("/user/login")

user_regis_login/templates/user_login/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'user_login/style.css' %}">
  <title>Login</title>
</head>
<body>
  <!-- untuk mendapatkan data User-->
  <!-- Triknya biar tidak kelihatan di browser, properti css display dibuat jadi none -->
  <!-- {% for user in users %}
    <span class="emails">{{user.email}}</span>
    <span class="passwords">{{user.password}}</span>
  {% endfor %} -->
      
<form action="" method="post">
    <div class="logo">
      <h1>VaksinYuk</h1>
    </div>
  <h2>Login</h2>
  <div class="icons">
    <label class="icon" for="id_email">
    </label>
    <label class="icon" for="id_password">
    </label>
  </div>
    {% csrf_token %}
    <label for="id_email">Email</label>
    <input type="email" name="email" id="id_email" required placeholder="Masukkan email anda">
    <h6 id="email_message">Email anda valid</h6>
    <label for="id_password">Password</label>
    <input type="password" name="password" id="id_password" required placeholder="Masukkan password anda">
    <h6 id="password_message">Maaf password tidak sesuai</h6>
    <button type="submit"><span>Login</span></button>
    <h5>Jika anda belum mempunyai akun, silahkan <a href="{% url 'user_regis' %}">register</a></h5>
  </form>
  <script type="text/javascript">
    let json = JSON.parse("{{json|escapejs}}");
    // console.log(json)
  </script>
  <script src="{% static 'jquery/jquery.js' %}"></script>
  <script src="{% static 'user_login/script.js' %}"></script>
</body>
</html>